export const environment = {
  production: false,
  testEnv: true,
  providers: 'app',
  bucketName: "2542-srm-dev",
  alertfromID: 'SRM_Dev',
  TestMailIDs: "d.santosh.madhuri;s.chintaparti;ritesh.kuma;m.zaheer.shaikh;b.lakshmi.radha;a.priyadarshini;amar.sanganna",
  S3UploadServiceURL: 'https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/s3uploadservice',
  stage: true,
  CookieUrl: 'https://ciocloudspacdn.ciostage.accenture.com/cookiesservice?Domain=workplace.servicerelationshipmanagement.ciodev.accenture.com',
  accountGetUrl: 'https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/accountservice',
  packageGetUrl: 'https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/packageservice',
  scoreGetUrl: 'https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/scoreservice',
  taskGetUrl: 'https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/taskservice',
  redirectUri: 'https://workplace.servicerelationshipmanagement.ciodev.accenture.com',
  alertserviceUrl: "https://bi8bsd7epd.execute-api.us-east-1.amazonaws.com/Development/alertservice",
  authorizationLocal: "",
  peopleProfilePictureURL: 'https://collabhub.accenture.com/People/ProfilePicture/',
  ProfilePicturedefaultpath: 'https://people.accenture.com/misc/staticcontentwrapper.ashx?filenm=defaultprofilephoto.png',
  workCompletionReportURL: "https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fCarpet_Consolidated_WCC&rs:Command=Render",
  dashboardReportURL: "https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fSRM_Dashboard&rs:Command=Render",
  dataEntryReportURL: "https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fDaily_Entry_Check&rs:Command=Render",
  workCompletionDetailsReportURL: "https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fDaily_Carpet_Entry_Status&rs:Command=Render",
  detailedDashboardReportURL: "https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fDetailed_Dashboard&rs:Command=Render",
  taskDetailsReportURL:"https://bi5.ciostage.accenture.com/ReportServer/Pages/ReportViewer.aspx?%2f2542_Service+Management+Data+Reporting+System%2fReports%2fTask_Details&rs:Command=Render",
  ZLSDLURL: "https://workplace.servicerelationshipmanagement.ciodev.accenture.com/transaction/approval/",
  VendorURL: "https://workplace.servicerelationshipmanagement.ciodev.accenture.com/transaction/vendor/",
  LogoutURL: "https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0"
};
