

export const configuration = {
    Daily: 'Daily',
    Weekly: 'Weekly',
    Fortnightly: 'Fortnightly',
    Monthly: 'Monthly',
    BiMonthly: 'Bi Monthly',
    Quaterly: 'Quarterly',
    HalfYearly: 'Half Yearly',
    Yearly: 'Yearly',
    Met: 'Met',
    NotMet: 'Not Met',
    NA: 'NA',
    Draft: 'Draft',
    NewSubmission: 'New Submission',
    ZLSDLRejected: 'ZL/SDL Rejected',
    ZLSDLApproved: 'ZL/SDL Approved',  
    VendorDisagreed: 'Vendor Disagreed',
    AgreedandClosed : 'Agreed and Closed',
    Submitted:'Submitted',
    Success: 'Success',
    Mandatory: 'Mandatory',
    Alert: 'Alert',
    Confirm: 'Confirm',
    MandatoryMessage: 'Please select all the mandatory fields.',
    SaveMessage: 'Saved successfully.',
    UpdateMessage: 'Updated successfully.',
    RecordExistsMessage: 'Record already exists.',
    VendorExistsMessage: 'Role already exists.',
    OLAMandatorySelection: 'Please provide feedback for OLA.',
    OLANotNAValidation: 'For this selected Function Met/ Not Met has been scored in Other Frequency.',
    OLANAValidation: 'For this selected Function NA has been scored in Other Frequency.',
    GenerateScoreValidation: 'Please save records to generate score.',
    GenerateScoreValidationOLA: 'Please provide feedback for all OLA for all Frequency.',
    GenerateScoreValidationTask: 'Task Data entry is not done for this Facility, Vendor and Period Date.',
    SubmitValidation: 'Please provide comments.',
    TransactionSubmission: 'Scorecard submitted successfully.',
    TransactionApproved: 'Scorecard approved successfully.',
    TransactionRejected: 'Scorecard rejected successfully.',
    TransactionAgreed: 'Scorecard agreed and closed successfully.',
    TransactionDisagreed: 'Scorecard disagreed successfully.',
    FornightPackageValidation: 'Score can be generated on',
    ConfirmSubmission : 'Do you want to Submit the Scorecard ?',
    ConfirmSubmissionMontly: 'Submitting scorecard will resubmit all the related scorecard for entire month. Do you want to Submit the Scorecard ?',
    ConfirmSubmissionMontlyNA : 'None of the Scorecard falling under frequency Daily/Weekly/Fortnihtly has been resubmitted. Do you want to Submit the Scorecard ?',
    ConfirmSubmissionMontlyA : 'Few of the Scorecard falling under frequency Daily/Weekly/Fortnihtly have been resubmitted. Do you want to Submit the Scorecard ?',
    ConfirmApprove : 'Do you want to Approve the Scorecard ?',
    ConfirmReject : 'Do you want to Reject the Scorecard ?',
    ConfirmAgree : 'Do you want to Agree the Scorecard ?',
    ConfirmDisagree : 'Do you want to Disagree the Scorecard ?',
    ConfirmDelete : 'Are you sure you want to delete? This will delete the role including all the packages and facilities mapped to the user.',
    Carpet: 'Carpet',
    TransactionEnable: 'Scorecard has been enabled for resubmission.',
    TransactionSubmitRevalidate: 'Scorecard is already submitted.',
    TransactionApproveRevalidate: 'Scorecard is already approved/rejected.',
    TransactionAgreedRevalidate: 'Scorecard is already agreed/disagreed.',

    TaskSaveValidation: 'Please select atleast one Task to save',
    ConfirmTaskAdd: 'Do you want to Save the Task ?',
    NoTaskMessage: 'No Task created for this Facility and Tower in Task Master Module',
    TaskSaveReValidation: 'Selected Task is alreday saved.',

    NoAccessMessage: 'You are not authorized to view this page',
    WeigthageExceeds:'Weightage exceeds more than 100%.',
    FunctionUpdate:'Function updated successfully.',
    WeightageZero : 'Weightage should be greater than zero.',
    AreaZero:'Area should be greater than zero.',
    SubmitPackageValidation:'Package already submitted.',
    SubmitPackage:'Package submitted successfully.',
    AddOneFunction:'Please add atleast one function to submit the package.',
    WeightageMessage:'Weightage should be 100% to submit the package.',
    
    ReportURLSuffix:'&rs:Command=Render&rc:Parameters=false',

    CategoryME: 'M&E',
    CategorySoftServices: 'Soft services',
    RoleCE: 'Chief Engineer',
    RoleDE: 'Duty Engineer',
    RoleDEGroup: 'Duty Engineer Group',
    RoleDM: 'Duty Manager',
    RoleDMGroup: 'Duty Manager Group',
    RoleWM: 'Workplace Manager',
    RoleMELead: 'City Engineer',//'M&E Lead',
    RoleCityLead: 'City Lead',
    RoleZL: 'Engineering Zonal Lead',
    RoleSDL: 'Service Delivery Lead',
    RoleVendor: 'Vendor',
    RoleSRMAdmin: 'SRM Admin',
    RoleLeadership: 'Leadership',

    href: '/',
    SessionTimeOutMessage: 'Session has expired. Please login to continue.',

    TasksPackage: 'TasksPackage',
    FullAccess: 'FullAccess'
};
  